USE [master];
GO
CREATE LOGIN siga 
    WITH PASSWORD    = N'msiga',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO
EXEC sp_addsrvrolemember 
    @loginame = N'siga', 
    @rolename = N'sysadmin';
GO

CREATE DATABASE [TAF] ON  PRIMARY 
( NAME = N'TAF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATATAF.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TAF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATATAF_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE Latin1_General_BIN
GO
ALTER DATABASE [TAF] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [TAF] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TAF] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TAF] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TAF] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TAF] SET ARITHABORT OFF 
GO
ALTER DATABASE [TAF] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TAF] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [TAF] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TAF] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TAF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TAF] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TAF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TAF] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TAF] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TAF] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TAF] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TAF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TAF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TAF] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TAF] SET  READ_WRITE 
GO
ALTER DATABASE [TAF] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TAF] SET  MULTI_USER 
GO
ALTER DATABASE [TAF] SET PAGE_VERIFY CHECKSUM  
GO
USE [TAF]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TAF] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
