version: "3"
volumes: 
  dados:
services:
  mssql:
    container_name: mssql
    image: "microsoft/mssql-server-linux:2017-CU13"
    volumes: 
      - dados:/var/opt/mssql/data
      - ./mssql:/mssql
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rd2019' -d Master -i /mssql/checkdb.sql
    environment:
      SA_PASSWORD: "P@ssw0rd2019"
      ACCEPT_EULA: "Y"
  dbaccess:
    container_name: dbaccess
    image: "msullivancm/dbaccess:20190520"
    environment: 
      - PENV=P12123
    ports: 
      - 7890:7890
    depends_on: 
      - mssql
  totvslic:
    container_name: totvslic
    image: "msullivancm/totvslic:20190427"
    ports: 
      - 5555:5555
      - 2234:2234
  p12123bin:
    container_name: p12123bin
    image: "msullivancm/p12123bin:20190520"
    volumes: 
      - ./p12123protheus_data/protheus_data:/totvs/protheus/protheus_data 
    ports: 
      - 1234:1234
    depends_on: 
      - dbaccess
      - totvslic
